# Generated by Django 4.0.6 on 2022-08-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
